name: MVVMCleanArchitecture-sample

options:
  bundleIdPrefix: com.miseri.MVVMCleanArchitecture-sample
  deploymentTarget:
  iOS: 14.3
  xcodeVersion: "12.5"

packages:

targets:
  MVVMCleanArchitecture-sample:
    type: application
    platform: iOS

    preBuildScripts:
      # SwiftLintで静的解析と自動修正
      - path: ./Scripts/XcodeGen/swiftlint.sh
        name: Run SwiftLint

      # SpellCheckerでスペルチェック
      - path: ./Scripts/XcodeGen/spellchecker.sh
        name: Run SpellChecker
